In [1]:
# !pip install yfinance

In [2]:
# dependencies
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine, Column, Integer, String, Date, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from datetime import date
import sqlite3

In [3]:
# Creates a connection to our DB. if file doesn't exist, we create it
# echo=True is verbose
engine = create_engine("sqlite:///stocks.sqlite", echo=True)
conn = engine.connect()
session = Session(engine)
Base = declarative_base()

# # Define our pet table
# probably deprecated after i found out about df.to_sql method
# class stock(Base):
#     __tablename__ = 'stock'
#     id = Column(Integer, primary_key=True)
#     name = Column(String)
#     type = Column(String)
#     date = Column(Date)
# # creates table
# Base.metadata.create_all(engine)

In [4]:
# choose tickers here
# tickerStrings = ['AAPL', 'MSFT','TSLA','META','TTCF']

In [5]:
#import csv file with the list of S&P 500 companies
splist = pd.read_csv("sp500_constituents.csv")
# print df
splist

    Symbol                 Name                  Sector
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4     ABMD              Abiomed             Health Care
..     ...                  ...                     ...
500    YUM          Yum! Brands  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [6]:
#s&p500 tickers
sp500 = splist.rename(columns={'Symbol':'Ticker'})
# print df
sp500

    Ticker                 Name                  Sector
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4     ABMD              Abiomed             Health Care
..     ...                  ...                     ...
500    YUM          Yum! Brands  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [7]:
# variable for the list for the for loop
tickerStrings = sp500['Ticker']

# yfinance code to separate tickers into pretty dataframe
df_list = list()
for ticker in tickerStrings:
    data = yf.download(ticker, group_by="Ticker", period='2y')
    data['Ticker'] = ticker  # add this column because the dataframe doesn't contain a column with the ticker
    
    df_list.append(data)

# combine all dataframes into a single dataframe
tickerDf = pd.concat(df_list)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BRK.B: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BF.B: No data found for this date range, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- DISCA: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- DISCK: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- INFO: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- KSU: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- PBCT: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- VIAC: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- WLTW: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- XLNX: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
# reset index to prepare for merge
tickerindex = tickerDf.reset_index()

tickerindex

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,2020-07-13,154.350006,156.929993,154.160004,154.800003,144.537048,2217800.0,MMM
1,2020-07-14,154.800003,159.229996,153.919998,158.539993,148.029099,3198900.0,MMM
2,2020-07-15,159.979996,161.380005,159.250000,159.330002,148.766724,3472300.0,MMM
3,2020-07-16,159.250000,160.910004,158.039993,160.500000,149.859146,1801500.0,MMM
4,2020-07-17,160.860001,161.559998,159.509995,159.830002,149.233566,2551700.0,MMM
...,...,...,...,...,...,...,...,...
248743,2022-07-05,172.279999,174.289993,169.550003,174.250000,174.250000,1853100.0,ZTS
248744,2022-07-06,174.869995,179.880005,174.399994,178.500000,178.500000,1883300.0,ZTS
248745,2022-07-07,177.720001,180.000000,177.509995,179.100006,179.100006,1317300.0,ZTS
248746,2022-07-08,177.500000,179.470001,177.080002,177.979996,177.979996,1301700.0,ZTS
248747,2022-07-11,177.850006,178.455002,176.529999,177.039993,177.039993,978304.0,ZTS

In [9]:
# merge the sp500 df to get add the ticker name
mergeticker = tickerindex.merge(sp500, how = 'right', on = 'Ticker')

mergeticker

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,Name,Sector
0,2020-07-13,154.350006,156.929993,154.160004,154.800003,144.537048,2217800.0,MMM,3M,Industrials
1,2020-07-14,154.800003,159.229996,153.919998,158.539993,148.029099,3198900.0,MMM,3M,Industrials
2,2020-07-15,159.979996,161.380005,159.250000,159.330002,148.766724,3472300.0,MMM,3M,Industrials
3,2020-07-16,159.250000,160.910004,158.039993,160.500000,149.859146,1801500.0,MMM,3M,Industrials
4,2020-07-17,160.860001,161.559998,159.509995,159.830002,149.233566,2551700.0,MMM,3M,Industrials
...,...,...,...,...,...,...,...,...,...,...
248753,2022-07-05,172.279999,174.289993,169.550003,174.250000,174.250000,1853100.0,ZTS,Zoetis,Health Care
248754,2022-07-06,174.869995,179.880005,174.399994,178.500000,178.500000,1883300.0,ZTS,Zoetis,Health Care
248755,2022-07-07,177.720001,180.000000,177.509995,179.100006,179.100006,1317300.0,ZTS,Zoetis,Health Care
248756,2022-07-08,177.500000,179.470001,177.080002,177.979996,177.979996,1301700.0,ZTS,Zoetis,Health Care
248757,2022-07-11,177.850006,178.455002,176.529999,177.039993,177.039993,978304.0,ZTS,Zoetis,Health Care

In [10]:
# dropping columns
closeticker = mergeticker.drop(columns =['High','Low','Open','Adj Close'])

# set index to date
cleanedticker = closeticker.set_index('Date')

cleanedticker

                 Close     Volume Ticker    Name       Sector
Date
2020-07-13  154.800003  2217800.0    MMM      3M  Industrials
2020-07-14  158.539993  3198900.0    MMM      3M  Industrials
2020-07-15  159.330002  3472300.0    MMM      3M  Industrials
2020-07-16  160.500000  1801500.0    MMM      3M  Industrials
2020-07-17  159.830002  2551700.0    MMM      3M  Industrials
...                ...        ...    ...     ...          ...
2022-07-05  174.250000  1853100.0    ZTS  Zoetis  Health Care
2022-07-06  178.500000  1883300.0    ZTS  Zoetis  Health Care
2022-07-07  179.100006  1317300.0    ZTS  Zoetis  Health Care
2022-07-08  177.979996  1301700.0    ZTS  Zoetis  Health Care
2022-07-11  177.039993   978304.0    ZTS  Zoetis  Health Care

[248758 rows x 5 columns]

In [11]:
# cleanedticker["__id"] = 1
cleanedticker.insert(0, '__id', range(0, len(cleanedticker)))
# cleanedticker.reset_index()
# cleanedticker["__id"] = cleanedticker.index

In [12]:
cleanedticker

              __id       Close     Volume Ticker    Name       Sector
Date
2020-07-13       0  154.800003  2217800.0    MMM      3M  Industrials
2020-07-14       1  158.539993  3198900.0    MMM      3M  Industrials
2020-07-15       2  159.330002  3472300.0    MMM      3M  Industrials
2020-07-16       3  160.500000  1801500.0    MMM      3M  Industrials
2020-07-17       4  159.830002  2551700.0    MMM      3M  Industrials
...            ...         ...        ...    ...     ...          ...
2022-07-05  248753  174.250000  1853100.0    ZTS  Zoetis  Health Care
2022-07-06  248754  178.500000  1883300.0    ZTS  Zoetis  Health Care
2022-07-07  248755  179.100006  1317300.0    ZTS  Zoetis  Health Care
2022-07-08  248756  177.979996  1301700.0    ZTS  Zoetis  Health Care
2022-07-11  248757  177.039993   978304.0    ZTS  Zoetis  Health Care

[248758 rows x 6 columns]

In [13]:
with sqlite3.connect('stocks.sqlite') as con:
    cleanedticker.to_sql('stocks', con=con, dtype={'__id': 'INTEGER PRIMARY KEY AUTOINCREMENT'})

In [14]:
# this will push dataframe to sql, creating a table if none exists
# cleanedticker.to_sql('stocks', conn, if_exists='append')

In [15]:
cleanedticker.head()

            __id       Close     Volume Ticker Name       Sector
Date
2020-07-13     0  154.800003  2217800.0    MMM   3M  Industrials
2020-07-14     1  158.539993  3198900.0    MMM   3M  Industrials
2020-07-15     2  159.330002  3472300.0    MMM   3M  Industrials
2020-07-16     3  160.500000  1801500.0    MMM   3M  Industrials
2020-07-17     4  159.830002  2551700.0    MMM   3M  Industrials

In [16]:
#import csv file with the list of top 100 crypto currencies from yahoo finance
cryptolist = pd.read_csv("yfcryptolist.csv").rename(columns={'Unnamed: 0':'index'})

# print to check df
cryptolist

    index              Name    Ticker
0       0       Bitcoin USD   BTC-USD
1       1      Ethereum USD   ETH-USD
2       2        Tether USD  USDT-USD
3       3      USD Coin USD  USDC-USD
4       4  Binance Coin USD   BNB-USD
..    ...               ...       ...
95     95          Celo USD  CELO-USD
96     96          Kava USD  KAVA-USD
97     97       Arweave USD    AR-USD
98     98          Mina USD  MINA-USD
99     99           Amp USD   AMP-USD

[100 rows x 3 columns]

In [17]:
# set variable name for list for the for loop
cryptoStrings = cryptolist['Ticker']

In [18]:
# yfinance code to separate tickers into pretty dataframe
df_list2 = list()
for crypto in cryptoStrings:
    data2 = yf.download(crypto, group_by="Ticker", period='2y')
    # add this column because the dataframe doesn't contain a column with the ticker
    data2['Ticker'] = crypto 
    
    df_list2.append(data2)

# combine all dataframes into a single dataframe
cryptoDf = pd.concat(df_list2)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [19]:
# print df
cryptoDf

,Open,High,Low,Close,Adj Close,Volume,Ticker
Date,,,,,,,
2020-07-11,9277.511719,9293.532227,9199.485352,9240.346680,9240.346680,13249910444,BTC-USD
2020-07-12,9241.054688,9319.418945,9197.450195,9276.500000,9276.500000,14452361907,BTC-USD
2020-07-13,9277.205078,9306.405273,9224.292969,9243.614258,9243.614258,17519821266,BTC-USD
2020-07-14,9238.703125,9283.841797,9171.661133,9243.213867,9243.213867,18085038362,BTC-USD
2020-07-15,9241.897461,9275.325195,9171.933594,9192.836914,9192.836914,15844731575,BTC-USD
...,...,...,...,...,...,...,...
2022-07-07,0.009128,0.009406,0.009092,0.009316,0.009316,8082951,AMP-USD
2022-07-08,0.009310,0.009445,0.009074,0.009211,0.009211,5985245,AMP-USD
2022-07-09,0.009202,0.009328,0.009121,0.009141,0.009141,5078295,AMP-USD
2022-07-10,0.009141,0.009583,0.009084,0.009159,0.009159,9384899,AMP-USD
2022-07-11,0.009135,0.009135,0.008755,0.008800,0.008800,4926253,AMP-USD

In [20]:
# reset index to prepare for merge and rename ticker column
cryptoindex = cryptoDf.reset_index().rename(columns={"Ticker":"Ticker-drop"})

cryptoindex

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker-drop
0,2020-07-11,9277.511719,9293.532227,9199.485352,9240.346680,9240.346680,13249910444,BTC-USD
1,2020-07-12,9241.054688,9319.418945,9197.450195,9276.500000,9276.500000,14452361907,BTC-USD
2,2020-07-13,9277.205078,9306.405273,9224.292969,9243.614258,9243.614258,17519821266,BTC-USD
3,2020-07-14,9238.703125,9283.841797,9171.661133,9243.213867,9243.213867,18085038362,BTC-USD
4,2020-07-15,9241.897461,9275.325195,9171.933594,9192.836914,9192.836914,15844731575,BTC-USD
...,...,...,...,...,...,...,...,...
64609,2022-07-07,0.009128,0.009406,0.009092,0.009316,0.009316,8082951,AMP-USD
64610,2022-07-08,0.009310,0.009445,0.009074,0.009211,0.009211,5985245,AMP-USD
64611,2022-07-09,0.009202,0.009328,0.009121,0.009141,0.009141,5078295,AMP-USD
64612,2022-07-10,0.009141,0.009583,0.009084,0.009159,0.009159,9384899,AMP-USD
64613,2022-07-11,0.009135,0.009135,0.008755,0.008800,0.008800,4926253,AMP-USD

In [21]:
# split the hyphen from crypto ticker for the final crypto df, rename columns, and reset index to prepare for merge
tickersplit = cryptolist['Ticker'].str.split('-' ,expand=True).rename(columns={0:'Ticker', 1: 'drop'}).reset_index()
tickersplit

    index Ticker drop
0       0    BTC  USD
1       1    ETH  USD
2       2   USDT  USD
3       3   USDC  USD
4       4    BNB  USD
..    ...    ...  ...
95     95   CELO  USD
96     96   KAVA  USD
97     97     AR  USD
98     98   MINA  USD
99     99    AMP  USD

[100 rows x 3 columns]

In [22]:
# split the space from crypto name for the final crypto df, rename columns, and reset index to prepare for merge
namesplit = cryptolist['Name'].str.split(' ', expand = True).rename(columns={0:'Name', 1: 'drop'}).reset_index()
namesplit

    index      Name  drop     2     3
0       0   Bitcoin   USD  None  None
1       1  Ethereum   USD  None  None
2       2    Tether   USD  None  None
3       3       USD  Coin   USD  None
4       4   Binance  Coin   USD  None
..    ...       ...   ...   ...   ...
95     95      Celo   USD  None  None
96     96      Kava   USD  None  None
97     97   Arweave   USD  None  None
98     98      Mina   USD  None  None
99     99       Amp   USD  None  None

[100 rows x 5 columns]

In [23]:
# merge the two dfs
rename_merge = tickersplit.merge(namesplit, how='right', on='index').drop(columns =['drop_x','drop_y',2,3])

rename_merge

    index Ticker      Name
0       0    BTC   Bitcoin
1       1    ETH  Ethereum
2       2   USDT    Tether
3       3   USDC       USD
4       4    BNB   Binance
..    ...    ...       ...
95     95   CELO      Celo
96     96   KAVA      Kava
97     97     AR   Arweave
98     98   MINA      Mina
99     99    AMP       Amp

[100 rows x 3 columns]

In [24]:
# merge the cryptolist df to prepare for the merge with the crypto data df and rename the columns
mergecrylist = rename_merge.merge(cryptolist, how = 'right', on= 'index')\
            .rename(columns={'Name_x':'Name-drop','Ticker_x':'Ticker','Name_y':'Name','Ticker_y':'Ticker-drop'})

mergecrylist

    index Ticker Name-drop              Name Ticker-drop
0       0    BTC   Bitcoin       Bitcoin USD     BTC-USD
1       1    ETH  Ethereum      Ethereum USD     ETH-USD
2       2   USDT    Tether        Tether USD    USDT-USD
3       3   USDC       USD      USD Coin USD    USDC-USD
4       4    BNB   Binance  Binance Coin USD     BNB-USD
..    ...    ...       ...               ...         ...
95     95   CELO      Celo          Celo USD    CELO-USD
96     96   KAVA      Kava          Kava USD    KAVA-USD
97     97     AR   Arweave       Arweave USD      AR-USD
98     98   MINA      Mina          Mina USD    MINA-USD
99     99    AMP       Amp           Amp USD     AMP-USD

[100 rows x 5 columns]

In [25]:
# final merge between the data df and the name list df and drop the unnecessary columns
crypto_cleaned =cryptoindex.merge(mergecrylist, how= 'right', on='Ticker-drop')\
                .drop(columns=['Open','High','Low','Adj Close', 'index', 'Ticker-drop', 'Name-drop'])\
                .set_index('Date')
crypto_cleaned["Sector"] = "Crypto Currency"

crypto_cleaned

                  Close       Volume Ticker         Name           Sector
Date
2020-07-11  9240.346680  13249910444    BTC  Bitcoin USD  Crypto Currency
2020-07-12  9276.500000  14452361907    BTC  Bitcoin USD  Crypto Currency
2020-07-13  9243.614258  17519821266    BTC  Bitcoin USD  Crypto Currency
2020-07-14  9243.213867  18085038362    BTC  Bitcoin USD  Crypto Currency
2020-07-15  9192.836914  15844731575    BTC  Bitcoin USD  Crypto Currency
...                 ...          ...    ...          ...              ...
2022-07-07     0.009316      8082951    AMP      Amp USD  Crypto Currency
2022-07-08     0.009211      5985245    AMP      Amp USD  Crypto Currency
2022-07-09     0.009141      5078295    AMP      Amp USD  Crypto Currency
2022-07-10     0.009159      9384899    AMP      Amp USD  Crypto Currency
2022-07-11     0.008800      4926253    AMP      Amp USD  Crypto Currency

[64614 rows x 5 columns]

In [26]:
# export to sql
crypto_cleaned.to_sql('stocks', conn, if_exists='append')

2022-07-11 19:20:05,689 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("stocks")
2022-07-11 19:20:05,691 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-11 19:20:05,743 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-11 19:20:06,557 INFO sqlalchemy.engine.Engine INSERT INTO stocks ("Date", "Close", "Volume", "Ticker", "Name", "Sector") VALUES (?, ?, ?, ?, ?, ?)
2022-07-11 19:20:06,559 INFO sqlalchemy.engine.Engine [generated in 0.74674s] (('2020-07-11 00:00:00.000000', 9240.3466796875, 13249910444, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-12 00:00:00.000000', 9276.5, 14452361907, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-13 00:00:00.000000', 9243.6142578125, 17519821266, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-14 00:00:00.000000', 9243.2138671875, 18085038362, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-15 00:00:00.000000', 9192.8369140625, 15844731575, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-16 00:00:00.000000', 9132.2275390625, 15713967523, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-17 00:00:00.000000', 9151.392578125, 13944570749, 'BTC', 'Bitcoin USD', 'Crypto Currency'), ('2020-07-18 00:00:00.000000', 9159.0400390625, 12252601475, 'BTC', 'Bitcoin USD', 'Crypto Currency')  ... displaying 10 of 64614 total bound parameter sets ...  ('2022-07-10 00:00:00.000000', 0.009158999659121037, 9384899, 'AMP', 'Amp USD', 'Crypto Currency'), ('2022-07-11 00:00:00.000000', 0.00879967026412487, 4926253, 'AMP', 'Amp USD', 'Crypto Currency'))
2022-07-11 19:20:08,159 INFO sqlalchemy.engine.Engine COMMIT