In [1]:
# !pip install yfinance

In [2]:
# dependencies
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine, Column, Integer, String, Date, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from datetime import date
import sqlite3
from datetime import datetime

In [3]:
# Creates a connection to our DB. if file doesn't exist, we create it
# echo=True is verbose
engine = create_engine("sqlite:///pstocks.sqlite", echo=True)
conn = engine.connect()
session = Session(engine)
Base = declarative_base()

# # Define our pet table
# probably deprecated after i found out about df.to_sql method
# class stock(Base):
#     __tablename__ = 'stock'
#     id = Column(Integer, primary_key=True)
#     name = Column(String)
#     type = Column(String)
#     date = Column(Date)
# # creates table
# Base.metadata.create_all(engine)

In [4]:
# choose tickers here
# tickerStrings = ['AAPL', 'MSFT','TSLA','META','TTCF']

In [5]:
#import csv file with the list of S&P 500 companies
splist = pd.read_csv("sp500_constituents.csv")
# print df
splist

    Symbol                 Name                  Sector
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4     ABMD              Abiomed             Health Care
..     ...                  ...                     ...
500    YUM          Yum! Brands  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [6]:
#s&p500 tickers
sp500 = splist.rename(columns={'Symbol':'Ticker'})
# print df
sp500

    Ticker                 Name                  Sector
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4     ABMD              Abiomed             Health Care
..     ...                  ...                     ...
500    YUM          Yum! Brands  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [7]:
# variable for the list for the for loop
tickerStrings = sp500['Ticker']

# yfinance code to separate tickers into pretty dataframe
df_list = list()
for ticker in tickerStrings:
    data = yf.download(ticker, group_by="Ticker", period='2y')
    data['Ticker'] = ticker  # add this column because the dataframe doesn't contain a column with the ticker
    
    df_list.append(data)

# combine all dataframes into a single dataframe
tickerDf = pd.concat(df_list)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BLL: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BRK.B: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BF.B: No data found for this date range, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- DISCA: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- DISCK: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- INFO: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- KSU: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- PBCT: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- VIAC: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- WLTW: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- XLNX: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
# reset index to prepare for merge
tickerindex = tickerDf.reset_index()

tickerindex

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,2020-07-16,159.250000,160.910004,158.039993,160.500000,149.859161,1801500.0,MMM
1,2020-07-17,160.860001,161.559998,159.509995,159.830002,149.233582,2551700.0,MMM
2,2020-07-20,158.850006,158.869995,156.369995,156.369995,146.002975,1790100.0,MMM
3,2020-07-21,157.000000,159.630005,156.990005,157.800003,147.338181,2757200.0,MMM
4,2020-07-22,157.429993,159.929993,157.020004,158.710007,148.187851,1899600.0,MMM
...,...,...,...,...,...,...,...,...
248736,2022-07-11,177.850006,178.460007,176.529999,177.039993,177.039993,1008700.0,ZTS
248737,2022-07-12,176.699997,179.210007,173.149994,173.809998,173.809998,1643000.0,ZTS
248738,2022-07-13,170.399994,170.970001,167.050003,167.809998,167.809998,2271500.0,ZTS
248739,2022-07-14,166.929993,170.940002,165.750000,170.789993,170.789993,1570500.0,ZTS
248740,2022-07-15,173.570007,175.160004,173.169998,174.539993,174.539993,2409303.0,ZTS

In [9]:
# merge the sp500 df to get add the ticker name
mergeticker = tickerindex.merge(sp500, how = 'right', on = 'Ticker')

mergeticker

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,Name,Sector
0,2020-07-16,159.250000,160.910004,158.039993,160.500000,149.859161,1801500.0,MMM,3M,Industrials
1,2020-07-17,160.860001,161.559998,159.509995,159.830002,149.233582,2551700.0,MMM,3M,Industrials
2,2020-07-20,158.850006,158.869995,156.369995,156.369995,146.002975,1790100.0,MMM,3M,Industrials
3,2020-07-21,157.000000,159.630005,156.990005,157.800003,147.338181,2757200.0,MMM,3M,Industrials
4,2020-07-22,157.429993,159.929993,157.020004,158.710007,148.187851,1899600.0,MMM,3M,Industrials
...,...,...,...,...,...,...,...,...,...,...
248747,2022-07-11,177.850006,178.460007,176.529999,177.039993,177.039993,1008700.0,ZTS,Zoetis,Health Care
248748,2022-07-12,176.699997,179.210007,173.149994,173.809998,173.809998,1643000.0,ZTS,Zoetis,Health Care
248749,2022-07-13,170.399994,170.970001,167.050003,167.809998,167.809998,2271500.0,ZTS,Zoetis,Health Care
248750,2022-07-14,166.929993,170.940002,165.750000,170.789993,170.789993,1570500.0,ZTS,Zoetis,Health Care
248751,2022-07-15,173.570007,175.160004,173.169998,174.539993,174.539993,2409303.0,ZTS,Zoetis,Health Care

In [10]:
#find percent change from day to day
pct_stock = mergeticker['Close'].pct_change()*100

#add percent change to df
mergeticker['Close % Change'] = pct_stock

# dropping Nan rows
dropnan = mergeticker.dropna()
dropnan

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,Name,Sector,Close % Change
1,2020-07-17,160.860001,161.559998,159.509995,159.830002,149.233582,2551700.0,MMM,3M,Industrials,-0.417444
2,2020-07-20,158.850006,158.869995,156.369995,156.369995,146.002975,1790100.0,MMM,3M,Industrials,-2.164804
3,2020-07-21,157.000000,159.630005,156.990005,157.800003,147.338181,2757200.0,MMM,3M,Industrials,0.914503
4,2020-07-22,157.429993,159.929993,157.020004,158.710007,148.187851,1899600.0,MMM,3M,Industrials,0.576682
5,2020-07-23,159.000000,159.649994,158.360001,159.289993,148.729385,2695100.0,MMM,3M,Industrials,0.365438
...,...,...,...,...,...,...,...,...,...,...,...
248747,2022-07-11,177.850006,178.460007,176.529999,177.039993,177.039993,1008700.0,ZTS,Zoetis,Health Care,-0.528151
248748,2022-07-12,176.699997,179.210007,173.149994,173.809998,173.809998,1643000.0,ZTS,Zoetis,Health Care,-1.824444
248749,2022-07-13,170.399994,170.970001,167.050003,167.809998,167.809998,2271500.0,ZTS,Zoetis,Health Care,-3.452045
248750,2022-07-14,166.929993,170.940002,165.750000,170.789993,170.789993,1570500.0,ZTS,Zoetis,Health Care,1.775815
248751,2022-07-15,173.570007,175.160004,173.169998,174.539993,174.539993,2409303.0,ZTS,Zoetis,Health Care,2.195679

In [11]:
# dropping columns
closeticker = dropnan.drop(columns =['High','Low','Open','Adj Close'])

# set index to date
cleanedticker = closeticker.set_index('Date')

cleanedticker

                 Close     Volume Ticker    Name       Sector  Close % Change
Date
2020-07-17  159.830002  2551700.0    MMM      3M  Industrials       -0.417444
2020-07-20  156.369995  1790100.0    MMM      3M  Industrials       -2.164804
2020-07-21  157.800003  2757200.0    MMM      3M  Industrials        0.914503
2020-07-22  158.710007  1899600.0    MMM      3M  Industrials        0.576682
2020-07-23  159.289993  2695100.0    MMM      3M  Industrials        0.365438
...                ...        ...    ...     ...          ...             ...
2022-07-11  177.039993  1008700.0    ZTS  Zoetis  Health Care       -0.528151
2022-07-12  173.809998  1643000.0    ZTS  Zoetis  Health Care       -1.824444
2022-07-13  167.809998  2271500.0    ZTS  Zoetis  Health Care       -3.452045
2022-07-14  170.789993  1570500.0    ZTS  Zoetis  Health Care        1.775815
2022-07-15  174.539993  2409303.0    ZTS  Zoetis  Health Care        2.195679

[248738 rows x 6 columns]

In [12]:
# cleanedticker["__id"] = 1
cleanedticker.insert(0, '__id', range(0, len(cleanedticker)))
# cleanedticker.reset_index()
# cleanedticker["__id"] = cleanedticker.index

In [13]:
with sqlite3.connect('pstocks.sqlite') as con:
    cleanedticker.to_sql('pstocks', con=con, dtype={'__id': 'INTEGER PRIMARY KEY AUTOINCREMENT'})

C:\Users\yhuan\anaconda3\lib\site-packages\pandas\core\generic.py:2872: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(

In [14]:
# this will push dataframe to sql, creating a table if none exists
# cleanedticker.to_sql('stocks', conn, if_exists='append')

In [15]:
cleanedticker.head()

,__id,Close,Volume,Ticker,Name,Sector,Close % Change
Date,,,,,,,
2020-07-17,0,159.830002,2551700.0,MMM,3M,Industrials,-0.417444
2020-07-20,1,156.369995,1790100.0,MMM,3M,Industrials,-2.164804
2020-07-21,2,157.800003,2757200.0,MMM,3M,Industrials,0.914503
2020-07-22,3,158.710007,1899600.0,MMM,3M,Industrials,0.576682
2020-07-23,4,159.289993,2695100.0,MMM,3M,Industrials,0.365438

In [16]:
#import csv file with the list of top 100 crypto currencies from yahoo finance
cryptolist = pd.read_csv("yfcryptolist.csv").rename(columns={'Unnamed: 0':'index'})

# print to check df
cryptolist

    index              Name    Ticker
0       0       Bitcoin USD   BTC-USD
1       1      Ethereum USD   ETH-USD
2       2        Tether USD  USDT-USD
3       3      USD Coin USD  USDC-USD
4       4  Binance Coin USD   BNB-USD
..    ...               ...       ...
95     95          Celo USD  CELO-USD
96     96          Kava USD  KAVA-USD
97     97       Arweave USD    AR-USD
98     98          Mina USD  MINA-USD
99     99           Amp USD   AMP-USD

[100 rows x 3 columns]

In [17]:
# set variable name for list for the for loop
cryptoStrings = cryptolist['Ticker']

In [18]:
# yfinance code to separate tickers into pretty dataframe
df_list2 = list()
for crypto in cryptoStrings:
    data2 = yf.download(crypto, group_by="Ticker", period='2y')
    # add this column because the dataframe doesn't contain a column with the ticker
    data2['Ticker'] = crypto 
    
    df_list2.append(data2)

# combine all dataframes into a single dataframe
cryptoDf = pd.concat(df_list2)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [19]:
# print df
cryptoDf

,Open,High,Low,Close,Adj Close,Volume,Ticker
Date,,,,,,,
2020-07-15,9241.897461,9275.325195,9171.933594,9192.836914,9192.836914,15844731575,BTC-USD
2020-07-16,9191.980469,9214.312500,9088.947266,9132.227539,9132.227539,15713967523,BTC-USD
2020-07-17,9131.812500,9182.253906,9089.202148,9151.392578,9151.392578,13944570749,BTC-USD
2020-07-18,9151.183594,9230.983398,9100.824219,9159.040039,9159.040039,12252601475,BTC-USD
2020-07-19,9158.005859,9201.398438,9097.632812,9185.817383,9185.817383,12939002784,BTC-USD
...,...,...,...,...,...,...,...
2022-07-11,0.009156,0.009156,0.008743,0.008844,0.008844,4977881,AMP-USD
2022-07-12,0.008842,0.009128,0.008763,0.008778,0.008778,8721514,AMP-USD
2022-07-13,0.008778,0.008943,0.008521,0.008870,0.008870,6845247,AMP-USD
2022-07-14,0.008871,0.008988,0.008627,0.008951,0.008951,5889119,AMP-USD
2022-07-15,0.008970,0.009196,0.008882,0.009040,0.009040,5873327,AMP-USD

In [20]:
# reset index to prepare for merge and rename ticker column
cryptoindex = cryptoDf.reset_index().rename(columns={"Ticker":"Ticker-drop"})

cryptoindex

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker-drop
0,2020-07-15,9241.897461,9275.325195,9171.933594,9192.836914,9192.836914,15844731575,BTC-USD
1,2020-07-16,9191.980469,9214.312500,9088.947266,9132.227539,9132.227539,15713967523,BTC-USD
2,2020-07-17,9131.812500,9182.253906,9089.202148,9151.392578,9151.392578,13944570749,BTC-USD
3,2020-07-18,9151.183594,9230.983398,9100.824219,9159.040039,9159.040039,12252601475,BTC-USD
4,2020-07-19,9158.005859,9201.398438,9097.632812,9185.817383,9185.817383,12939002784,BTC-USD
...,...,...,...,...,...,...,...,...
64739,2022-07-11,0.009156,0.009156,0.008743,0.008844,0.008844,4977881,AMP-USD
64740,2022-07-12,0.008842,0.009128,0.008763,0.008778,0.008778,8721514,AMP-USD
64741,2022-07-13,0.008778,0.008943,0.008521,0.008870,0.008870,6845247,AMP-USD
64742,2022-07-14,0.008871,0.008988,0.008627,0.008951,0.008951,5889119,AMP-USD
64743,2022-07-15,0.008970,0.009196,0.008882,0.009040,0.009040,5873327,AMP-USD

In [21]:
# split the hyphen from crypto ticker for the final crypto df, rename columns, and reset index to prepare for merge
tickersplit = cryptolist['Ticker'].str.split('-' ,expand=True).rename(columns={0:'Ticker', 1: 'drop'}).reset_index()
tickersplit

    index Ticker drop
0       0    BTC  USD
1       1    ETH  USD
2       2   USDT  USD
3       3   USDC  USD
4       4    BNB  USD
..    ...    ...  ...
95     95   CELO  USD
96     96   KAVA  USD
97     97     AR  USD
98     98   MINA  USD
99     99    AMP  USD

[100 rows x 3 columns]

In [22]:
# split the space from crypto name for the final crypto df, rename columns, and reset index to prepare for merge
namesplit = cryptolist['Name'].str.split(' ', expand = True).rename(columns={0:'Name', 1: 'drop'}).reset_index()
namesplit

    index      Name  drop     2     3
0       0   Bitcoin   USD  None  None
1       1  Ethereum   USD  None  None
2       2    Tether   USD  None  None
3       3       USD  Coin   USD  None
4       4   Binance  Coin   USD  None
..    ...       ...   ...   ...   ...
95     95      Celo   USD  None  None
96     96      Kava   USD  None  None
97     97   Arweave   USD  None  None
98     98      Mina   USD  None  None
99     99       Amp   USD  None  None

[100 rows x 5 columns]

In [23]:
# merge the two dfs
rename_merge = tickersplit.merge(namesplit, how='right', on='index').drop(columns =['drop_x','drop_y',2,3])

rename_merge

    index Ticker      Name
0       0    BTC   Bitcoin
1       1    ETH  Ethereum
2       2   USDT    Tether
3       3   USDC       USD
4       4    BNB   Binance
..    ...    ...       ...
95     95   CELO      Celo
96     96   KAVA      Kava
97     97     AR   Arweave
98     98   MINA      Mina
99     99    AMP       Amp

[100 rows x 3 columns]

In [24]:
# merge the cryptolist df to prepare for the merge with the crypto data df and rename the columns
mergecrylist = rename_merge.merge(cryptolist, how = 'right', on= 'index')\
            .rename(columns={'Name_x':'Name-drop','Ticker_x':'Ticker','Name_y':'Name','Ticker_y':'Ticker-drop'})

mergecrylist

    index Ticker Name-drop              Name Ticker-drop
0       0    BTC   Bitcoin       Bitcoin USD     BTC-USD
1       1    ETH  Ethereum      Ethereum USD     ETH-USD
2       2   USDT    Tether        Tether USD    USDT-USD
3       3   USDC       USD      USD Coin USD    USDC-USD
4       4    BNB   Binance  Binance Coin USD     BNB-USD
..    ...    ...       ...               ...         ...
95     95   CELO      Celo          Celo USD    CELO-USD
96     96   KAVA      Kava          Kava USD    KAVA-USD
97     97     AR   Arweave       Arweave USD      AR-USD
98     98   MINA      Mina          Mina USD    MINA-USD
99     99    AMP       Amp           Amp USD     AMP-USD

[100 rows x 5 columns]

In [25]:
# final merge between the data df and the name list df and drop the unnecessary columns
crypto_merge =cryptoindex.merge(mergecrylist, how= 'right', on='Ticker-drop')\
                .drop(columns=['Open','High','Low','Adj Close', 'index', 'Ticker-drop', 'Name-drop'])\
                .set_index('Date')
crypto_merge["Sector"] = "Crypto Currency"

crypto_merge

                  Close       Volume Ticker         Name           Sector
Date
2020-07-15  9192.836914  15844731575    BTC  Bitcoin USD  Crypto Currency
2020-07-16  9132.227539  15713967523    BTC  Bitcoin USD  Crypto Currency
2020-07-17  9151.392578  13944570749    BTC  Bitcoin USD  Crypto Currency
2020-07-18  9159.040039  12252601475    BTC  Bitcoin USD  Crypto Currency
2020-07-19  9185.817383  12939002784    BTC  Bitcoin USD  Crypto Currency
...                 ...          ...    ...          ...              ...
2022-07-11     0.008844      4977881    AMP      Amp USD  Crypto Currency
2022-07-12     0.008778      8721514    AMP      Amp USD  Crypto Currency
2022-07-13     0.008870      6845247    AMP      Amp USD  Crypto Currency
2022-07-14     0.008951      5889119    AMP      Amp USD  Crypto Currency
2022-07-15     0.009040      5873327    AMP      Amp USD  Crypto Currency

[64744 rows x 5 columns]

In [26]:
#find percent change from day to day
pct_crypto = crypto_merge['Close'].pct_change()*100

#add percent change to df
crypto_merge['Close % Change'] = pct_crypto

# dropping Nan rows
dropnan = crypto_merge.dropna()

crypto_cleaned = dropnan

crypto_cleaned

,Close,Volume,Ticker,Name,Sector,Close % Change
Date,,,,,,
2020-07-16,9132.227539,15713967523,BTC,Bitcoin USD,Crypto Currency,-0.659311
2020-07-17,9151.392578,13944570749,BTC,Bitcoin USD,Crypto Currency,0.209862
2020-07-18,9159.040039,12252601475,BTC,Bitcoin USD,Crypto Currency,0.083566
2020-07-19,9185.817383,12939002784,BTC,Bitcoin USD,Crypto Currency,0.292360
2020-07-20,9164.231445,13755604146,BTC,Bitcoin USD,Crypto Currency,-0.234992
...,...,...,...,...,...,...
2022-07-11,0.008844,4977881,AMP,Amp USD,Crypto Currency,-3.439233
2022-07-12,0.008778,8721514,AMP,Amp USD,Crypto Currency,-0.746269
2022-07-13,0.008870,6845247,AMP,Amp USD,Crypto Currency,1.048072
2022-07-14,0.008951,5889119,AMP,Amp USD,Crypto Currency,0.913190
2022-07-15,0.009040,5873327,AMP,Amp USD,Crypto Currency,0.999213

In [27]:
# export to sql
crypto_cleaned.to_sql('pstocks', conn, if_exists='append')

2022-07-15 19:55:49,683 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("pstocks")
2022-07-15 19:55:49,683 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-15 19:55:49,724 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-15 19:55:50,216 INFO sqlalchemy.engine.Engine INSERT INTO pstocks ("Date", "Close", "Volume", "Ticker", "Name", "Sector", "Close % Change") VALUES (?, ?, ?, ?, ?, ?, ?)
2022-07-15 19:55:50,216 INFO sqlalchemy.engine.Engine [generated in 0.42885s] (('2020-07-16 00:00:00.000000', 9132.2275390625, 15713967523, 'BTC', 'Bitcoin USD', 'Crypto Currency', -0.6593108913667822), ('2020-07-17 00:00:00.000000', 9151.392578125, 13944570749, 'BTC', 'Bitcoin USD', 'Crypto Currency', 0.2098616025556055), ('2020-07-18 00:00:00.000000', 9159.0400390625, 12252601475, 'BTC', 'Bitcoin USD', 'Crypto Currency', 0.08356608977502233), ('2020-07-19 00:00:00.000000', 9185.8173828125, 12939002784, 'BTC', 'Bitcoin USD', 'Crypto Currency', 0.2923597193133398), ('2020-07-20 00:00:00.000000', 9164.2314453125, 13755604146, 'BTC', 'Bitcoin USD', 'Crypto Currency', -0.23499201650132306), ('2020-07-21 00:00:00.000000', 9374.8876953125, 18069581956, 'BTC', 'Bitcoin USD', 'Crypto Currency', 2.298678850016933), ('2020-07-22 00:00:00.000000', 9525.36328125, 16532254884, 'BTC', 'Bitcoin USD', 'Crypto Currency', 1.6050921443329758), ('2020-07-23 00:00:00.000000', 9581.072265625, 18146399002, 'BTC', 'Bitcoin USD', 'Crypto Currency', 0.584848921034431)  ... displaying 10 of 64486 total bound parameter sets ...  ('2022-07-14 00:00:00.000000', 0.008950999937951565, 5889119, 'AMP', 'Amp USD', 'Crypto Currency', 0.9131896065660783), ('2022-07-15 00:00:00.000000', 0.009040439501404762, 5873327, 'AMP', 'Amp USD', 'Crypto Currency', 0.9992130943268229))
2022-07-15 19:55:51,268 INFO sqlalchemy.engine.Engine COMMIT

In [28]:
sqlBubble = pd.read_sql('SELECT * FROM pstocks', con=conn)
sqlBubble

2022-07-15 19:55:51,360 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("SELECT * FROM pstocks")
2022-07-15 19:55:51,361 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-15 19:55:51,362 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("SELECT * FROM pstocks")
2022-07-15 19:55:51,362 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-15 19:55:51,363 INFO sqlalchemy.engine.Engine SELECT * FROM pstocks
2022-07-15 19:55:51,363 INFO sqlalchemy.engine.Engine [raw sql] ()

,Date,__id,Close,Volume,Ticker,Name,Sector,Close % Change
0,2020-07-17 00:00:00,0,159.830002,2551700.0,MMM,3M,Industrials,-0.417444
1,2020-07-20 00:00:00,1,156.369995,1790100.0,MMM,3M,Industrials,-2.164804
2,2020-07-21 00:00:00,2,157.800003,2757200.0,MMM,3M,Industrials,0.914503
3,2020-07-22 00:00:00,3,158.710007,1899600.0,MMM,3M,Industrials,0.576682
4,2020-07-23 00:00:00,4,159.289993,2695100.0,MMM,3M,Industrials,0.365438
...,...,...,...,...,...,...,...,...
313219,2022-07-11 00:00:00.000000,313219,0.008844,4977881.0,AMP,Amp USD,Crypto Currency,-3.439233
313220,2022-07-12 00:00:00.000000,313220,0.008778,8721514.0,AMP,Amp USD,Crypto Currency,-0.746269
313221,2022-07-13 00:00:00.000000,313221,0.008870,6845247.0,AMP,Amp USD,Crypto Currency,1.048072
313222,2022-07-14 00:00:00.000000,313222,0.008951,5889119.0,AMP,Amp USD,Crypto Currency,0.913190
313223,2022-07-15 00:00:00.000000,313223,0.009040,5873327.0,AMP,Amp USD,Crypto Currency,0.999213

In [29]:
sqlBubble["Date"] = pd.to_datetime(sqlBubble['Date']).dt.date
sqlBubble

,Date,__id,Close,Volume,Ticker,Name,Sector,Close % Change
0,2020-07-17,0,159.830002,2551700.0,MMM,3M,Industrials,-0.417444
1,2020-07-20,1,156.369995,1790100.0,MMM,3M,Industrials,-2.164804
2,2020-07-21,2,157.800003,2757200.0,MMM,3M,Industrials,0.914503
3,2020-07-22,3,158.710007,1899600.0,MMM,3M,Industrials,0.576682
4,2020-07-23,4,159.289993,2695100.0,MMM,3M,Industrials,0.365438
...,...,...,...,...,...,...,...,...
313219,2022-07-11,313219,0.008844,4977881.0,AMP,Amp USD,Crypto Currency,-3.439233
313220,2022-07-12,313220,0.008778,8721514.0,AMP,Amp USD,Crypto Currency,-0.746269
313221,2022-07-13,313221,0.008870,6845247.0,AMP,Amp USD,Crypto Currency,1.048072
313222,2022-07-14,313222,0.008951,5889119.0,AMP,Amp USD,Crypto Currency,0.913190
313223,2022-07-15,313223,0.009040,5873327.0,AMP,Amp USD,Crypto Currency,0.999213

In [30]:
with sqlite3.connect('stocks.sqlite') as con:
    sqlBubble.to_sql('stocks', con=con, dtype={'__id': 'INTEGER PRIMARY KEY AUTOINCREMENT'})

C:\Users\yhuan\anaconda3\lib\site-packages\pandas\core\generic.py:2872: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(

array([datetime.date(2020, 7, 17), datetime.date(2020, 7, 20),
       datetime.date(2020, 7, 21), datetime.date(2020, 7, 22),
       datetime.date(2020, 7, 23), datetime.date(2020, 7, 24),
       datetime.date(2020, 7, 27), datetime.date(2020, 7, 28),
       datetime.date(2020, 7, 29), datetime.date(2020, 7, 30),
       datetime.date(2020, 7, 31), datetime.date(2020, 8, 3),
       datetime.date(2020, 8, 4), datetime.date(2020, 8, 5),
       datetime.date(2020, 8, 6), datetime.date(2020, 8, 7),
       datetime.date(2020, 8, 10), datetime.date(2020, 8, 11),
       datetime.date(2020, 8, 12), datetime.date(2020, 8, 13),
       datetime.date(2020, 8, 14), datetime.date(2020, 8, 17),
       datetime.date(2020, 8, 18), datetime.date(2020, 8, 19),
       datetime.date(2020, 8, 20), datetime.date(2020, 8, 21),
       datetime.date(2020, 8, 24), datetime.date(2020, 8, 25),
       datetime.date(2020, 8, 26), datetime.date(2020, 8, 27),
       datetime.date(2020, 8, 28), datetime.date(2020, 8, 31),
       datetime.date(2020, 9, 1), datetime.date(2020, 9, 2),
       datetime.date(2020, 9, 3), datetime.date(2020, 9, 4),
       datetime.date(2020, 9, 8), datetime.date(2020, 9, 9),
       datetime.date(2020, 9, 10), datetime.date(2020, 9, 11),
       datetime.date(2020, 9, 14), datetime.date(2020, 9, 15),
       datetime.date(2020, 9, 16), datetime.date(2020, 9, 17),
       datetime.date(2020, 9, 18), datetime.date(2020, 9, 21),
       datetime.date(2020, 9, 22), datetime.date(2020, 9, 23),
       datetime.date(2020, 9, 24), datetime.date(2020, 9, 25),
       datetime.date(2020, 9, 28), datetime.date(2020, 9, 29),
       datetime.date(2020, 9, 30), datetime.date(2020, 10, 1),
       datetime.date(2020, 10, 2), datetime.date(2020, 10, 5),
       datetime.date(2020, 10, 6), datetime.date(2020, 10, 7),
       datetime.date(2020, 10, 8), datetime.date(2020, 10, 9),
       datetime.date(2020, 10, 12), datetime.date(2020, 10, 13),
       datetime.date(2020, 10, 14), datetime.date(2020, 10, 15),
       datetime.date(2020, 10, 16), datetime.date(2020, 10, 19),
       datetime.date(2020, 10, 20), datetime.date(2020, 10, 21),
       datetime.date(2020, 10, 22), datetime.date(2020, 10, 23),
       datetime.date(2020, 10, 26), datetime.date(2020, 10, 27),
       datetime.date(2020, 10, 28), datetime.date(2020, 10, 29),
       datetime.date(2020, 10, 30), datetime.date(2020, 11, 2),
       datetime.date(2020, 11, 3), datetime.date(2020, 11, 4),
       datetime.date(2020, 11, 5), datetime.date(2020, 11, 6),
       datetime.date(2020, 11, 9), datetime.date(2020, 11, 10),
       datetime.date(2020, 11, 11), datetime.date(2020, 11, 12),
       datetime.date(2020, 11, 13), datetime.date(2020, 11, 16),
       datetime.date(2020, 11, 17), datetime.date(2020, 11, 18),
       datetime.date(2020, 11, 19), datetime.date(2020, 11, 20),
       datetime.date(2020, 11, 23), datetime.date(2020, 11, 24),
       datetime.date(2020, 11, 25), datetime.date(2020, 11, 27),
       datetime.date(2020, 11, 30), datetime.date(2020, 12, 1),
       datetime.date(2020, 12, 2), datetime.date(2020, 12, 3),
       datetime.date(2020, 12, 4), datetime.date(2020, 12, 7),
       datetime.date(2020, 12, 8), datetime.date(2020, 12, 9),
       datetime.date(2020, 12, 10), datetime.date(2020, 12, 11),
       datetime.date(2020, 12, 14), datetime.date(2020, 12, 15),
       datetime.date(2020, 12, 16), datetime.date(2020, 12, 17),
       datetime.date(2020, 12, 18), datetime.date(2020, 12, 21),
       datetime.date(2020, 12, 22), datetime.date(2020, 12, 23),
       datetime.date(2020, 12, 24), datetime.date(2020, 12, 28),
       datetime.date(2020, 12, 29), datetime.date(2020, 12, 30),
       datetime.date(2020, 12, 31), datetime.date(2021, 1, 4),
       datetime.date(2021, 1, 5), datetime.date(2021, 1, 6),
       datetime.date(2021, 1, 7), datetime.date(2021, 1, 8),
       datetime.date(2021, 1, 11), datetime.date(2021, 1, 12),
       datetime.date(2021, 1, 13), datetime.date(2021, 1, 14),
       datetime.date(2021, 1, 15), datetime.date(2021, 1, 19),
       datetime.date(2021, 1, 20), datetime.date(2021, 1, 21),
       datetime.date(2021, 1, 22), datetime.date(2021, 1, 25),
       datetime.date(2021, 1, 26), datetime.date(2021, 1, 27),
       datetime.date(2021, 1, 28), datetime.date(2021, 1, 29),
       datetime.date(2021, 2, 1), datetime.date(2021, 2, 2),
       datetime.date(2021, 2, 3), datetime.date(2021, 2, 4),
       datetime.date(2021, 2, 5), datetime.date(2021, 2, 8),
       datetime.date(2021, 2, 9), datetime.date(2021, 2, 10),
       datetime.date(2021, 2, 11), datetime.date(2021, 2, 12),
       datetime.date(2021, 2, 16), datetime.date(2021, 2, 17),
       datetime.date(2021, 2, 18), datetime.date(2021, 2, 19),
       datetime.date(2021, 2, 22), datetime.date(2021, 2, 23),
       datetime.date(2021, 2, 24), datetime.date(2021, 2, 25),
       datetime.date(2021, 2, 26), datetime.date(2021, 3, 1),
       datetime.date(2021, 3, 2), datetime.date(2021, 3, 3),
       datetime.date(2021, 3, 4), datetime.date(2021, 3, 5),
       datetime.date(2021, 3, 8), datetime.date(2021, 3, 9),
       datetime.date(2021, 3, 10), datetime.date(2021, 3, 11),
       datetime.date(2021, 3, 12), datetime.date(2021, 3, 15),
       datetime.date(2021, 3, 16), datetime.date(2021, 3, 17),
       datetime.date(2021, 3, 18), datetime.date(2021, 3, 19),
       datetime.date(2021, 3, 22), datetime.date(2021, 3, 23),
       datetime.date(2021, 3, 24), datetime.date(2021, 3, 25),
       datetime.date(2021, 3, 26), datetime.date(2021, 3, 29),
       datetime.date(2021, 3, 30), datetime.date(2021, 3, 31),
       datetime.date(2021, 4, 1), datetime.date(2021, 4, 5),
       datetime.date(2021, 4, 6), datetime.date(2021, 4, 7),
       datetime.date(2021, 4, 8), datetime.date(2021, 4, 9),
       datetime.date(2021, 4, 12), datetime.date(2021, 4, 13),
       datetime.date(2021, 4, 14), datetime.date(2021, 4, 15),
       datetime.date(2021, 4, 16), datetime.date(2021, 4, 19),
       datetime.date(2021, 4, 20), datetime.date(2021, 4, 21),
       datetime.date(2021, 4, 22), datetime.date(2021, 4, 23),
       datetime.date(2021, 4, 26), datetime.date(2021, 4, 27),
       datetime.date(2021, 4, 28), datetime.date(2021, 4, 29),
       datetime.date(2021, 4, 30), datetime.date(2021, 5, 3),
       datetime.date(2021, 5, 4), datetime.date(2021, 5, 5),
       datetime.date(2021, 5, 6), datetime.date(2021, 5, 7),
       datetime.date(2021, 5, 10), datetime.date(2021, 5, 11),
       datetime.date(2021, 5, 12), datetime.date(2021, 5, 13),
       datetime.date(2021, 5, 14), datetime.date(2021, 5, 17),
       datetime.date(2021, 5, 18), datetime.date(2021, 5, 19),
       datetime.date(2021, 5, 20), datetime.date(2021, 5, 21),
       datetime.date(2021, 5, 24), datetime.date(2021, 5, 25),
       datetime.date(2021, 5, 26), datetime.date(2021, 5, 27),
       datetime.date(2021, 5, 28), datetime.date(2021, 6, 1),
       datetime.date(2021, 6, 2), datetime.date(2021, 6, 3),
       datetime.date(2021, 6, 4), datetime.date(2021, 6, 7),
       datetime.date(2021, 6, 8), datetime.date(2021, 6, 9),
       datetime.date(2021, 6, 10), datetime.date(2021, 6, 11),
       datetime.date(2021, 6, 14), datetime.date(2021, 6, 15),
       datetime.date(2021, 6, 16), datetime.date(2021, 6, 17),
       datetime.date(2021, 6, 18), datetime.date(2021, 6, 21),
       datetime.date(2021, 6, 22), datetime.date(2021, 6, 23),
       datetime.date(2021, 6, 24), datetime.date(2021, 6, 25),
       datetime.date(2021, 6, 28), datetime.date(2021, 6, 29),
       datetime.date(2021, 6, 30), datetime.date(2021, 7, 1),
       datetime.date(2021, 7, 2), datetime.date(2021, 7, 6),
       datetime.date(2021, 7, 7), datetime.date(2021, 7, 8),
       datetime.date(2021, 7, 9), datetime.date(2021, 7, 12),
       datetime.date(2021, 7, 13), datetime.date(2021, 7, 14),
       datetime.date(2021, 7, 15), datetime.date(2021, 7, 16),
       datetime.date(2021, 7, 19), datetime.date(2021, 7, 20),
       datetime.date(2021, 7, 21), datetime.date(2021, 7, 22),
       datetime.date(2021, 7, 23), datetime.date(2021, 7, 26),
       datetime.date(2021, 7, 27), datetime.date(2021, 7, 28),
       datetime.date(2021, 7, 29), datetime.date(2021, 7, 30),
       datetime.date(2021, 8, 2), datetime.date(2021, 8, 3),
       datetime.date(2021, 8, 4), datetime.date(2021, 8, 5),
       datetime.date(2021, 8, 6), datetime.date(2021, 8, 9),
       datetime.date(2021, 8, 10), datetime.date(2021, 8, 11),
       datetime.date(2021, 8, 12), datetime.date(2021, 8, 13),
       datetime.date(2021, 8, 16), datetime.date(2021, 8, 17),
       datetime.date(2021, 8, 18), datetime.date(2021, 8, 19),
       datetime.date(2021, 8, 20), datetime.date(2021, 8, 23),
       datetime.date(2021, 8, 24), datetime.date(2021, 8, 25),
       datetime.date(2021, 8, 26), datetime.date(2021, 8, 27),
       datetime.date(2021, 8, 30), datetime.date(2021, 8, 31),
       datetime.date(2021, 9, 1), datetime.date(2021, 9, 2),
       datetime.date(2021, 9, 3), datetime.date(2021, 9, 7),
       datetime.date(2021, 9, 8), datetime.date(2021, 9, 9),
       datetime.date(2021, 9, 10), datetime.date(2021, 9, 13),
       datetime.date(2021, 9, 14), datetime.date(2021, 9, 15),
       datetime.date(2021, 9, 16), datetime.date(2021, 9, 17),
       datetime.date(2021, 9, 20), datetime.date(2021, 9, 21),
       datetime.date(2021, 9, 22), datetime.date(2021, 9, 23),
       datetime.date(2021, 9, 24), datetime.date(2021, 9, 27),
       datetime.date(2021, 9, 28), datetime.date(2021, 9, 29),
       datetime.date(2021, 9, 30), datetime.date(2021, 10, 1),
       datetime.date(2021, 10, 4), datetime.date(2021, 10, 5),
       datetime.date(2021, 10, 6), datetime.date(2021, 10, 7),
       datetime.date(2021, 10, 8), datetime.date(2021, 10, 11),
       datetime.date(2021, 10, 12), datetime.date(2021, 10, 13),
       datetime.date(2021, 10, 14), datetime.date(2021, 10, 15),
       datetime.date(2021, 10, 18), datetime.date(2021, 10, 19),
       datetime.date(2021, 10, 20), datetime.date(2021, 10, 21),
       datetime.date(2021, 10, 22), datetime.date(2021, 10, 25),
       datetime.date(2021, 10, 26), datetime.date(2021, 10, 27),
       datetime.date(2021, 10, 28), datetime.date(2021, 10, 29),
       datetime.date(2021, 11, 1), datetime.date(2021, 11, 2),
       datetime.date(2021, 11, 3), datetime.date(2021, 11, 4),
       datetime.date(2021, 11, 5), datetime.date(2021, 11, 8),
       datetime.date(2021, 11, 9), datetime.date(2021, 11, 10),
       datetime.date(2021, 11, 11), datetime.date(2021, 11, 12),
       datetime.date(2021, 11, 15), datetime.date(2021, 11, 16),
       datetime.date(2021, 11, 17), datetime.date(2021, 11, 18),
       datetime.date(2021, 11, 19), datetime.date(2021, 11, 22),
       datetime.date(2021, 11, 23), datetime.date(2021, 11, 24),
       datetime.date(2021, 11, 26), datetime.date(2021, 11, 29),
       datetime.date(2021, 11, 30), datetime.date(2021, 12, 1),
       datetime.date(2021, 12, 2), datetime.date(2021, 12, 3),
       datetime.date(2021, 12, 6), datetime.date(2021, 12, 7),
       datetime.date(2021, 12, 8), datetime.date(2021, 12, 9),
       datetime.date(2021, 12, 10), datetime.date(2021, 12, 13),
       datetime.date(2021, 12, 14), datetime.date(2021, 12, 15),
       datetime.date(2021, 12, 16), datetime.date(2021, 12, 17),
       datetime.date(2021, 12, 20), datetime.date(2021, 12, 21),
       datetime.date(2021, 12, 22), datetime.date(2021, 12, 23),
       datetime.date(2021, 12, 27), datetime.date(2021, 12, 28),
       datetime.date(2021, 12, 29), datetime.date(2021, 12, 30),
       datetime.date(2021, 12, 31), datetime.date(2022, 1, 3),
       datetime.date(2022, 1, 4), datetime.date(2022, 1, 5),
       datetime.date(2022, 1, 6), datetime.date(2022, 1, 7),
       datetime.date(2022, 1, 10), datetime.date(2022, 1, 11),
       datetime.date(2022, 1, 12), datetime.date(2022, 1, 13),
       datetime.date(2022, 1, 14), datetime.date(2022, 1, 18),
       datetime.date(2022, 1, 19), datetime.date(2022, 1, 20),
       datetime.date(2022, 1, 21), datetime.date(2022, 1, 24),
       datetime.date(2022, 1, 25), datetime.date(2022, 1, 26),
       datetime.date(2022, 1, 27), datetime.date(2022, 1, 28),
       datetime.date(2022, 1, 31), datetime.date(2022, 2, 1),
       datetime.date(2022, 2, 2), datetime.date(2022, 2, 3),
       datetime.date(2022, 2, 4), datetime.date(2022, 2, 7),
       datetime.date(2022, 2, 8), datetime.date(2022, 2, 9),
       datetime.date(2022, 2, 10), datetime.date(2022, 2, 11),
       datetime.date(2022, 2, 14), datetime.date(2022, 2, 15),
       datetime.date(2022, 2, 16), datetime.date(2022, 2, 17),
       datetime.date(2022, 2, 18), datetime.date(2022, 2, 22),
       datetime.date(2022, 2, 23), datetime.date(2022, 2, 24),
       datetime.date(2022, 2, 25), datetime.date(2022, 2, 28),
       datetime.date(2022, 3, 1), datetime.date(2022, 3, 2),
       datetime.date(2022, 3, 3), datetime.date(2022, 3, 4),
       datetime.date(2022, 3, 7), datetime.date(2022, 3, 8),
       datetime.date(2022, 3, 9), datetime.date(2022, 3, 10),
       datetime.date(2022, 3, 11), datetime.date(2022, 3, 14),
       datetime.date(2022, 3, 15), datetime.date(2022, 3, 16),
       datetime.date(2022, 3, 17), datetime.date(2022, 3, 18),
       datetime.date(2022, 3, 21), datetime.date(2022, 3, 22),
       datetime.date(2022, 3, 23), datetime.date(2022, 3, 24),
       datetime.date(2022, 3, 25), datetime.date(2022, 3, 28),
       datetime.date(2022, 3, 29), datetime.date(2022, 3, 30),
       datetime.date(2022, 3, 31), datetime.date(2022, 4, 1),
       datetime.date(2022, 4, 4), datetime.date(2022, 4, 5),
       datetime.date(2022, 4, 6), datetime.date(2022, 4, 7),
       datetime.date(2022, 4, 8), datetime.date(2022, 4, 11),
       datetime.date(2022, 4, 12), datetime.date(2022, 4, 13),
       datetime.date(2022, 4, 14), datetime.date(2022, 4, 18),
       datetime.date(2022, 4, 19), datetime.date(2022, 4, 20),
       datetime.date(2022, 4, 21), datetime.date(2022, 4, 22),
       datetime.date(2022, 4, 25), datetime.date(2022, 4, 26),
       datetime.date(2022, 4, 27), datetime.date(2022, 4, 28),
       datetime.date(2022, 4, 29), datetime.date(2022, 5, 2),
       datetime.date(2022, 5, 3), datetime.date(2022, 5, 4),
       datetime.date(2022, 5, 5), datetime.date(2022, 5, 6),
       datetime.date(2022, 5, 9), datetime.date(2022, 5, 10),
       datetime.date(2022, 5, 11), datetime.date(2022, 5, 12),
       datetime.date(2022, 5, 13), datetime.date(2022, 5, 16),
       datetime.date(2022, 5, 17), datetime.date(2022, 5, 18),
       datetime.date(2022, 5, 19), datetime.date(2022, 5, 20),
       datetime.date(2022, 5, 23), datetime.date(2022, 5, 24),
       datetime.date(2022, 5, 25), datetime.date(2022, 5, 26),
       datetime.date(2022, 5, 27), datetime.date(2022, 5, 31),
       datetime.date(2022, 6, 1), datetime.date(2022, 6, 2),
       datetime.date(2022, 6, 3), datetime.date(2022, 6, 6),
       datetime.date(2022, 6, 7), datetime.date(2022, 6, 8),
       datetime.date(2022, 6, 9), datetime.date(2022, 6, 10),
       datetime.date(2022, 6, 13), datetime.date(2022, 6, 14),
       datetime.date(2022, 6, 15), datetime.date(2022, 6, 16),
       datetime.date(2022, 6, 17), datetime.date(2022, 6, 21),
       datetime.date(2022, 6, 22), datetime.date(2022, 6, 23),
       datetime.date(2022, 6, 24), datetime.date(2022, 6, 27),
       datetime.date(2022, 6, 28), datetime.date(2022, 6, 29),
       datetime.date(2022, 6, 30), datetime.date(2022, 7, 1),
       datetime.date(2022, 7, 5), datetime.date(2022, 7, 6),
       datetime.date(2022, 7, 7), datetime.date(2022, 7, 8),
       datetime.date(2022, 7, 11), datetime.date(2022, 7, 12),
       datetime.date(2022, 7, 13), datetime.date(2022, 7, 14),
       datetime.date(2022, 7, 15), datetime.date(2020, 7, 16),
       datetime.date(2020, 7, 18), datetime.date(2020, 7, 19),
       datetime.date(2020, 7, 25), datetime.date(2020, 7, 26),
       datetime.date(2020, 8, 1), datetime.date(2020, 8, 2),
       datetime.date(2020, 8, 8), datetime.date(2020, 8, 9),
       datetime.date(2020, 8, 15), datetime.date(2020, 8, 16),
       datetime.date(2020, 8, 22), datetime.date(2020, 8, 23),
       datetime.date(2020, 8, 29), datetime.date(2020, 8, 30),
       datetime.date(2020, 9, 5), datetime.date(2020, 9, 6),
       datetime.date(2020, 9, 7), datetime.date(2020, 9, 12),
       datetime.date(2020, 9, 13), datetime.date(2020, 9, 19),
       datetime.date(2020, 9, 20), datetime.date(2020, 9, 26),
       datetime.date(2020, 9, 27), datetime.date(2020, 10, 3),
       datetime.date(2020, 10, 4), datetime.date(2020, 10, 10),
       datetime.date(2020, 10, 11), datetime.date(2020, 10, 17),
       datetime.date(2020, 10, 18), datetime.date(2020, 10, 24),
       datetime.date(2020, 10, 25), datetime.date(2020, 10, 31),
       datetime.date(2020, 11, 1), datetime.date(2020, 11, 7),
       datetime.date(2020, 11, 8), datetime.date(2020, 11, 14),
       datetime.date(2020, 11, 15), datetime.date(2020, 11, 21),
       datetime.date(2020, 11, 22), datetime.date(2020, 11, 26),
       datetime.date(2020, 11, 28), datetime.date(2020, 11, 29),
       datetime.date(2020, 12, 5), datetime.date(2020, 12, 6),
       datetime.date(2020, 12, 12), datetime.date(2020, 12, 13),
       datetime.date(2020, 12, 19), datetime.date(2020, 12, 20),
       datetime.date(2020, 12, 25), datetime.date(2020, 12, 26),
       datetime.date(2020, 12, 27), datetime.date(2021, 1, 1),
       datetime.date(2021, 1, 2), datetime.date(2021, 1, 3),
       datetime.date(2021, 1, 9), datetime.date(2021, 1, 10),
       datetime.date(2021, 1, 16), datetime.date(2021, 1, 17),
       datetime.date(2021, 1, 18), datetime.date(2021, 1, 23),
       datetime.date(2021, 1, 24), datetime.date(2021, 1, 30),
       datetime.date(2021, 1, 31), datetime.date(2021, 2, 6),
       datetime.date(2021, 2, 7), datetime.date(2021, 2, 13),
       datetime.date(2021, 2, 14), datetime.date(2021, 2, 15),
       datetime.date(2021, 2, 20), datetime.date(2021, 2, 21),
       datetime.date(2021, 2, 27), datetime.date(2021, 2, 28),
       datetime.date(2021, 3, 6), datetime.date(2021, 3, 7),
       datetime.date(2021, 3, 13), datetime.date(2021, 3, 14),
       datetime.date(2021, 3, 20), datetime.date(2021, 3, 21),
       datetime.date(2021, 3, 27), datetime.date(2021, 3, 28),
       datetime.date(2021, 4, 2), datetime.date(2021, 4, 3),
       datetime.date(2021, 4, 4), datetime.date(2021, 4, 10),
       datetime.date(2021, 4, 11), datetime.date(2021, 4, 17),
       datetime.date(2021, 4, 18), datetime.date(2021, 4, 24),
       datetime.date(2021, 4, 25), datetime.date(2021, 5, 1),
       datetime.date(2021, 5, 2), datetime.date(2021, 5, 8),
       datetime.date(2021, 5, 9), datetime.date(2021, 5, 15),
       datetime.date(2021, 5, 16), datetime.date(2021, 5, 22),
       datetime.date(2021, 5, 23), datetime.date(2021, 5, 29),
       datetime.date(2021, 5, 30), datetime.date(2021, 5, 31),
       datetime.date(2021, 6, 5), datetime.date(2021, 6, 6),
       datetime.date(2021, 6, 12), datetime.date(2021, 6, 13),
       datetime.date(2021, 6, 19), datetime.date(2021, 6, 20),
       datetime.date(2021, 6, 26), datetime.date(2021, 6, 27),
       datetime.date(2021, 7, 3), datetime.date(2021, 7, 4),
       datetime.date(2021, 7, 5), datetime.date(2021, 7, 10),
       datetime.date(2021, 7, 11), datetime.date(2021, 7, 17),
       datetime.date(2021, 7, 18), datetime.date(2021, 7, 24),
       datetime.date(2021, 7, 25), datetime.date(2021, 7, 31),
       datetime.date(2021, 8, 1), datetime.date(2021, 8, 7),
       datetime.date(2021, 8, 8), datetime.date(2021, 8, 14),
       datetime.date(2021, 8, 15), datetime.date(2021, 8, 21),
       datetime.date(2021, 8, 22), datetime.date(2021, 8, 28),
       datetime.date(2021, 8, 29), datetime.date(2021, 9, 4),
       datetime.date(2021, 9, 5), datetime.date(2021, 9, 6),